apiVersion: v1
description: An open source, git-ops, zero-trust secrets encryption and decryption solution for Kubernetes applications
name: kamus
version: 0.4.16
home: https://kamus.soluto.io
icon: https://raw.githubusercontent.com/Soluto/kamus/master/images/logo.png
appVersion: 0.8.0.0
keywords:
  - gitops
  - secrets
sources:
  - https://github.com/Soluto/Kamus
maintainers:
  - name: omerlh
  - name: shaikatz
