kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kamus.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kamus.name" . }}-controller
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "kamus.name" . }}-controller
  apiGroup: rbac.authorization.k8s.io
