apiVersion: v1
kind: Service
metadata:
  name: {{ template "kamus.name" . }}-controller
  namespace: {{ template "kamus.namespace" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "kamus.name" . }}
    component: controller
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: 8888
      protocol: TCP
      name: kamus-controller

  selector:
    app: {{ template "kamus.name" . }}
    component: controller
    release: {{ .Release.Name }}
